apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8sAllowlistedImages
metadata:
  name: k8senforceallowlistedimages
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces: ["kube-system"]
  parameters:
    images:
      # Images for administrative-use
      - k8s.gcr.io/autoscaling/cluster-autoscaler
      - k8s.gcr.io/metrics-server-amd64
      - kubernetesui/dashboard
      - kubernetesui/metrics-scraper
      - grafana/grafana
      - prom/alertmanager
      - prom/prometheus
      - ghcr.io/aquasecurity
      - registry-auth.twistlock.com
      - openpolicyagent/gatekeeper
      - ghcr.io/dexidp
      - quay.io/argoproj/argocd
      - redis
      # Images for general-use
      - node
