apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8sWhitelistedImages
metadata:
  name: k8senforcewhitelistedimages
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces: ["kube-system"]
  parameters:
    images:
      # Images used by the infrastructure services inside the kubernetes cluster
      - k8s.gcr.io/autoscaling/cluster-autoscaler
      - k8s.gcr.io/metrics-server-amd64
      - kubernetesui/dashboard
      - kubernetesui/metrics-scraper
      - grafana/grafana
      - prom/alertmanager
      - prom/prometheus
      - openpolicyagent/gatekeeper
      # Images for support
      - busybox
      - kazuhikotsuji
